services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    networks:
      - monitoring
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://tempo:4318/v1/traces"
      SPRING_APPLICATION_NAME: "hapi-fhir"
    ports:
      - "9090:8080"
    depends_on:
      hapi-fhir-postgres:
        condition: service_healthy
    labels:
      - "logging=promtail"

  hapi-fhir-postgres:
    image: postgres:16-alpine
    container_name: hapi-fhir-postglkjres
    restart: always
    networks:
      - monitoring
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d hapi' || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    labels:
      - "logging=promtail"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    user: "0"
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "9091:9090"    # On utilise 9091 car ton HAPI FHIR occupe déjà le 9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'    # Garde 7 jours de données
    depends_on:
      - hapi-fhir-jpaserver-start
  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3200:3200"    # Interface Tempo
      - "4317:4317"    # OTLP gRPC (reçoit les traces)
      - "4318:4318"    # OTLP HTTP
    volumes:
      - ./config/tempo-config.yml:/etc/tempo.yml
      - tempo-data:/tmp/tempo
    command: -config.file=/etc/tempo.yml

volumes:
  hapi-fhir-postgres:
  loki-data:
  grafana-data:
  prometheus-data:
  tempo-data:
networks:
  monitoring:
    driver: bridge

